### PR TITLE
Add possibility to use own .conf files

### LINKED ISSUE #81: Need to be able to change update timer
Updating every 10 minutes is a waste of bandwidth, RAM and CPU cycles.

### PR DESCRIPTION
**Pull request by WhiteBahamut**
Closes #81 

Adding env vars to set location to custom .conf files. The custom files will be copied to `/etc/clamav` and overwrite the corresponding files.

### CODE REVIEW

**Comment by WhiteBahamut** [comment]
Please test and verify

**Comment by mko-x** [comment]
Thank you.

Maybe we should check if the file exists at the given path before copying it?

**Comment by WhiteBahamut** [comment]
I did not check on purpose. If the file does not exist a error massage is printed and the container stops (well it crashes, but thats the same here).  A check would basically do the some, just be more code :( So i jused stayed with default `cp`.

**Comment by mko-x** [comment]
Hmm, the debian:stretch-slim build fails:

```
...
Step 11/13 : RUN chown clamav:clamav bootstrap.sh check.sh && /etc/clamav/clamd.conf /etc/clamav/freshclam.conf     chmod u+x bootstrap.sh check.sh
 ---> Running in c83792e31142
/bin/sh: 1: /etc/clamav/clamd.conf: Permission denied
The command '/bin/sh -c chown clamav:clamav bootstrap.sh check.sh && /etc/clamav/clamd.conf /etc/clamav/freshclam.conf     chmod u+x bootstrap.sh check.sh' returned a non-zero code: 126
...
```

**Comment by WhiteBahamut** [comment]
mhhh hard for me to check stuff right now. PC broken :S Does it still happen? I always execute the build.sh and it worked for me

**Pull request merged**
